const Map<String, String> appStringsVi = {
  'appName': 'Digital Safe',
  'appTagline': 'Kho lưu trữ cá nhân của bạn an toàn tuyệt đối',
  'tabHome': 'Trang chủ',
  'tabRecent': 'Gần đây',
  'tabAdd': 'Thêm',
  'tabFavorites': 'Yêu thích',
  'tabSettings': 'Cài đặt',
  'navShop': 'Cửa hàng',
  'helloUser': 'Xin chào, {name} 👋',
  'searchDocuments': 'Tìm kiếm tài liệu...',
  'storageUsed': '{used} GB / {total} GB',
  'catCccd': 'CCCD/CMND',
  'catPassport': 'Passport',
  'catGplx': 'GPLX',
  'catDegree': 'Bằng cấp',
  'catCertificate': 'Chứng chỉ',
  'catInsurance': 'Bảo hiểm',
  'catWifi': 'Wifi Password',
  'catLicenseKey': 'License Key',
  'enterPin': 'Nhập mã PIN',
  'createPin': 'Tạo mã PIN',
  'confirmPin': 'Xác nhận PIN',
  'forgotPin': 'Quên PIN?',
  'forgotPinTitle': 'Đặt lại két sắt?',
  'forgotPinMessage': 'Không có PIN, dữ liệu đã mã hóa không thể khôi phục. Đặt lại sẽ xóa vĩnh viễn toàn bộ tài liệu trong két. Sau đó bạn có thể tạo PIN mới.',
  'resetVault': 'Đặt lại két sắt',
  'vaultResetDone': 'Đã đặt lại két sắt. Hãy tạo PIN mới.',
  'useFingerprint': 'Dùng vân tay',
  'usePinInstead': 'Dùng PIN thay thế',
  'unlockVault': 'Mở khóa két sắt',
  'setupVault': 'Thiết lập két sắt',
  'yourName': 'Tên của bạn',
  'enableBiometric': 'Bật xác thực vân tay',
  'pinMismatch': 'PIN không khớp',
  'wrongPin': 'PIN không đúng',
  'pinCreated': 'PIN đã được tạo',
  'addDocument': 'Thêm tài liệu',
  'editDocument': 'Sửa tài liệu',
  'documentTitle': 'Tiêu đề',
  'notes': 'Ghi chú',
  'selectFileOrPhoto': 'Chọn tệp hoặc chụp ảnh',
  'saveDocument': 'Lưu tài liệu',
  'share': 'Chia sẻ',
  'edit': 'Sửa',
  'delete': 'Xóa',
  'cancel': 'Hủy',
  'save': 'Lưu',
  'name': 'Tên',
  'category': 'Danh mục',
  'dateAdded': 'Ngày thêm',
  'expiryDate': 'Ngày hết hạn',
  'attachedFiles': 'Tệp đính kèm',
  'ssid': 'SSID',
  'password': 'Mật khẩu',
  'securityType': 'Loại bảo mật',
  'product': 'Sản phẩm',
  'licenseKey': 'License Key',
  'provider': 'Nhà cung cấp',
  'copy': 'Sao chép',
  'copied': 'Đã sao chép',
  'show': 'Hiện',
  'hide': 'Ẩn',
  'allDocuments': 'Tất cả tài liệu',
  'recentActivity': 'Hoạt động gần đây',
  'favorites': 'Yêu thích',
  'noDocuments': 'Chưa có tài liệu',
  'noFavorites': 'Chưa có yêu thích',
  'noActivity': 'Chưa có hoạt động',
  'activityAdded': 'Đã thêm',
  'activityViewed': 'Đã xem',
  'activityEdited': 'Đã sửa',
  'activityDeleted': 'Đã xóa',
  'activityFavorited': 'Yêu thích',
  'settings': 'Cài đặt',
  'security': 'Bảo mật',
  'fingerprintAuth': 'Xác thực vân tay',
  'autoLock': 'Tự động khóa',
  'changePin': 'Đổi PIN',
  'backup': 'Sao lưu',
  'backupData': 'Sao lưu dữ liệu',
  'restoreData': 'Khôi phục dữ liệu',
  'appearance': 'Giao diện',
  'changeTheme': 'Đổi giao diện',
  'language': 'Ngôn ngữ',
  'shop': 'Cửa hàng',
  'shopTitle': 'Cửa hàng Digital Safe',
  'shopDesc': 'Dùng điểm để mua theme, skin và tính năng premium',
  'yourCoins': 'Bạn có {count} điểm',
  'buyCoins': 'Mua thêm điểm',
  'buyCoinsDesc': 'Mua gói điểm qua Google Play',
  'earnCoins': 'Kiếm điểm miễn phí',
  'earnCoinsDesc': 'Đăng nhập hàng ngày, thêm tài liệu để nhận điểm',
  'dailyReward': 'Phần thưởng hàng ngày',
  'claimDaily': 'Nhận thưởng',
  'dailyClaimed': 'Đã nhận hôm nay',
  'spinWheel': 'Vòng quay may mắn',
  'spinNow': 'Quay ngay',
  'spinUsed': 'Đã quay hôm nay',
  'loginStreak': 'Chuỗi đăng nhập: {days} ngày',
  'shopRemoveAds': 'Loại bỏ quảng cáo',
  'shopRemoveAdsDesc': 'Trải nghiệm không quảng cáo vĩnh viễn',
  'shopThemeOcean': 'Theme Đại Dương',
  'shopThemeOceanDesc': 'Xanh biển sâu thẳm',
  'shopThemeEmerald': 'Theme Ngọc Lục',
  'shopThemeEmeraldDesc': 'Xanh lá sang trọng',
  'shopThemeRoyal': 'Theme Hoàng Gia',
  'shopThemeRoyalDesc': 'Tím hoàng gia',
  'shopThemeCrimson': 'Theme Crimson',
  'shopThemeCrimsonDesc': 'Đỏ mạnh mẽ',
  'shopBgVault': 'Nền Vault',
  'shopBgVaultDesc': 'Nền két sắt bảo mật',
  'shopBgStars': 'Nền Sao',
  'shopBgStarsDesc': 'Bầu trời đêm đầy sao',
  'shopBgNeon': 'Nền Neon',
  'shopBgNeonDesc': 'Neon xanh rực rỡ',
  'shopBgAurora': 'Nền Aurora',
  'shopBgAuroraDesc': 'Cực quang đa sắc',
  'shopSkinSoft': 'Skin Mềm',
  'shopSkinSoftDesc': 'Bo góc mềm mại',
  'shopSkinGlass': 'Skin Kính',
  'shopSkinGlassDesc': 'Hiệu ứng kính mờ',
  'shopSkinBold': 'Skin Đậm',
  'shopSkinBoldDesc': 'Viền nổi bật',
  'shopFeatExport': 'Xuất dữ liệu',
  'shopFeatExportDesc': 'Xuất tài liệu ra file',
  'shopFeatUnlimited': 'Không giới hạn',
  'shopFeatUnlimitedDesc': 'Lưu tối đa 500 tài liệu',
  'shopFeatBackup': 'Sao lưu nâng cao',
  'shopFeatBackupDesc': 'Sao lưu và khôi phục nâng cao',
  'shopFeatExpiry': 'Cảnh báo hết hạn',
  'shopFeatExpiryDesc': 'Nhắc nhở trước ngày hết hạn',
  'shopMenuAll': 'Tất cả',
  'shopMenuPremium': 'Premium',
  'shopMenuThemes': 'Theme',
  'shopMenuBackgrounds': 'Hình nền',
  'shopMenuSkins': 'Skin',
  'shopMenuFeatures': 'Tính năng',
  'shopEmptyCategory': 'Không có mục nào',
  'shopOwned': 'Đã sở hữu',
  'shopBuy': 'Mua',
  'shopApply': 'Áp dụng',
  'shopActive': 'Đang dùng',
  'shopResetDefault': 'Mặc định',
  'shopInsufficientCoins': 'Không đủ điểm',
  'shopPurchaseSuccess': 'Mua thành công!',
  'shopAlreadyOwned': 'Đã sở hữu rồi',
  'purchaseSuccess': 'Mua thành công',
  'purchaseFailed': 'Mua thất bại',
  'coinsAdded': 'Đã thêm điểm',
  'coinsAddedWithBonus': 'Đã thêm điểm + bonus',
  'coinEarned': '+{amount} điểm',
  'coinRewardSub': 'Tổng số dư: {balance} điểm',
  'coins': 'điểm',
  'removeAdsUnlocked': 'Đã loại bỏ quảng cáo',
  'dailyRewardClaimed': 'Nhận thưởng hàng ngày',
  'docRewardEarned': 'Thưởng thêm tài liệu',
  'backupRewardEarned': 'Thưởng sao lưu',
  'spinRewardEarned': 'Thưởng vòng quay',
  'coinPack': 'Gói {num}',
  'coinAmountTotal': '{count} điểm',
  'coinBonusExtra': '{base} + {bonus} bonus',
  'hotDealBadge': 'HOT',
  'bestValueBadge': 'TỐT NHẤT',
  'firstPurchaseBadge': '+50%',
  'earnCoinsHint': 'Hoặc kiếm điểm miễn phí trong Cửa hàng',
  'processingPurchase': 'Đang xử lý...',
  'billingUnavailable': 'Thanh toán không khả dụng',
  'productsNotFound': 'Không tìm thấy sản phẩm',
  'openingBilling': 'Đang mở thanh toán...',
  'configTimeout': 'Hết thời gian tải cấu hình',
  'configNetworkError': 'Lỗi mạng khi tải cấu hình',
  'billingDisabledHint': 'Mua bằng điểm trong cửa hàng',
  'documentLimitReached': 'Đã đạt giới hạn tài liệu. Nâng cấp trong Cửa hàng.',
  'deleteConfirm': 'Xóa tài liệu này?',
  'privacyPolicy': 'Chính sách bảo mật',
  'version': 'Phiên bản {version}',
  'darkMode': 'Chế độ tối',
  'lightMode': 'Chế độ sáng',
  'minutes': '{count} phút',
  'oldPin': 'PIN cũ',
  'newPin': 'PIN mới',
  'pinChanged': 'Đã đổi PIN',
  'backupSuccess': 'Sao lưu thành công',
  'restoreSuccess': 'Khôi phục thành công',
  'restoreFailed': 'Khôi phục thất bại',
  'exportRequiresPremium': 'Cần mua tính năng Xuất dữ liệu',
  'documentsCount': '{count} tài liệu',
  'titleRequired': 'Vui lòng nhập tiêu đề tài liệu',
  'saveSuccess': 'Đã lưu tài liệu',
  'saveFailed': 'Lưu thất bại, thử lại',
  'promoHotDeal': 'DEAL HOT TUẦN NÀY',
  'promoTitle': 'Nâng cấp két sắt của bạn ✨',
  'promoHotDealDesc': 'Gói {pack} — nhận {coins} điểm (+ bonus tuần này)',
  'promoUnlockTarget': 'Sắp mở: {item} ({price} điểm)',
  'promoUnlockRemaining': 'Còn {count} điểm nữa là mở khóa!',
  'promoBuyNow': 'Mua coin ngay',
  'promoBuyShort': 'Mua',
  'promoCompactTitle': 'Deal hot — nhận thêm điểm',
  'purchasePromoTitle': 'Ưu đãi đặc biệt hôm nay',
  'purchasePromoDesc': 'Gói {pack} hot: {coins} điểm (bonus +{bonus})',
  'purchaseFirstBonus': 'Lần mua đầu +50% điểm — đừng bỏ lỡ!',
  'teaserPremiumTitle': 'Theme & tính năng Premium',
  'teaserPremiumDesc': 'Dùng điểm hoặc mua coin để mở khóa',
  'shopSubtitle': 'Mua theme, skin và tính năng cao cấp',
  'yourWallet': 'Ví điểm của bạn',
  'earnStepDaily': 'Đăng nhập nhận thưởng',
  'dailyRewardDone': 'Đã nhận hôm nay',
  'privacyPolicyTitle': 'Chính sách bảo mật Digital Safe',
  'privacyPolicyBody': 'Digital Safe lưu trữ dữ liệu cục bộ trên thiết bị của bạn với mã hóa AES-256. Chúng tôi không thu thập hay truyền tài liệu cá nhân lên máy chủ. Dữ liệu thanh toán được xử lý bởi Google Play. Ứng dụng yêu cầu quyền camera và ảnh để quét tài liệu.',
};
