const Map<String, String> appStringsEn = {
  'appName': 'Digital Safe',
  'appTagline': 'Your personal vault — absolutely secure',
  'tabHome': 'Home',
  'tabRecent': 'Recent',
  'tabAdd': 'Add',
  'tabFavorites': 'Favorites',
  'tabSettings': 'Settings',
  'navShop': 'Shop',
  'helloUser': 'Hello, {name} 👋',
  'searchDocuments': 'Search documents...',
  'storageUsed': '{used} GB / {total} GB',
  'catCccd': 'ID Card',
  'catPassport': 'Passport',
  'catGplx': 'Driver License',
  'catDegree': 'Degree',
  'catCertificate': 'Certificate',
  'catInsurance': 'Insurance',
  'catWifi': 'Wifi Password',
  'catLicenseKey': 'License Key',
  'enterPin': 'Enter PIN',
  'createPin': 'Create PIN',
  'confirmPin': 'Confirm PIN',
  'forgotPin': 'Forgot PIN?',
  'forgotPinTitle': 'Reset vault?',
  'forgotPinMessage': 'Without your PIN, encrypted documents cannot be recovered. Resetting will permanently delete all vault data. You can set a new PIN afterward.',
  'resetVault': 'Reset vault',
  'vaultResetDone': 'Vault reset. Create a new PIN.',
  'useFingerprint': 'Use fingerprint',
  'usePinInstead': 'Use PIN instead',
  'unlockVault': 'Unlock vault',
  'setupVault': 'Setup vault',
  'yourName': 'Your name',
  'enableBiometric': 'Enable fingerprint',
  'pinMismatch': 'PIN does not match',
  'wrongPin': 'Wrong PIN',
  'pinCreated': 'PIN created',
  'addDocument': 'Add document',
  'editDocument': 'Edit document',
  'documentTitle': 'Title',
  'notes': 'Notes',
  'selectFileOrPhoto': 'Select file or take photo',
  'saveDocument': 'Save document',
  'share': 'Share',
  'edit': 'Edit',
  'delete': 'Delete',
  'cancel': 'Cancel',
  'save': 'Save',
  'name': 'Name',
  'category': 'Category',
  'dateAdded': 'Date added',
  'expiryDate': 'Expiry date',
  'attachedFiles': 'Attached files',
  'ssid': 'SSID',
  'password': 'Password',
  'securityType': 'Security type',
  'product': 'Product',
  'licenseKey': 'License Key',
  'provider': 'Provider',
  'copy': 'Copy',
  'copied': 'Copied',
  'show': 'Show',
  'hide': 'Hide',
  'allDocuments': 'All documents',
  'recentActivity': 'Recent activity',
  'favorites': 'Favorites',
  'noDocuments': 'No documents yet',
  'noFavorites': 'No favorites yet',
  'noActivity': 'No activity yet',
  'activityAdded': 'Added',
  'activityViewed': 'Viewed',
  'activityEdited': 'Edited',
  'activityDeleted': 'Deleted',
  'activityFavorited': 'Favorited',
  'settings': 'Settings',
  'security': 'Security',
  'fingerprintAuth': 'Fingerprint auth',
  'autoLock': 'Auto lock',
  'changePin': 'Change PIN',
  'backup': 'Backup',
  'backupData': 'Backup data',
  'restoreData': 'Restore data',
  'appearance': 'Appearance',
  'changeTheme': 'Change theme',
  'language': 'Language',
  'shop': 'Shop',
  'shopTitle': 'Digital Safe Shop',
  'shopDesc': 'Use points to buy themes, skins and premium features',
  'yourCoins': 'You have {count} points',
  'buyCoins': 'Buy more points',
  'buyCoinsDesc': 'Purchase point packs via Google Play',
  'earnCoins': 'Earn free points',
  'earnCoinsDesc': 'Daily login and add documents to earn points',
  'dailyReward': 'Daily reward',
  'claimDaily': 'Claim',
  'dailyClaimed': 'Claimed today',
  'spinWheel': 'Lucky spin',
  'spinNow': 'Spin now',
  'spinUsed': 'Already spun today',
  'loginStreak': 'Login streak: {days} days',
  'shopRemoveAds': 'Remove ads',
  'shopRemoveAdsDesc': 'Ad-free experience forever',
  'shopThemeOcean': 'Ocean Theme',
  'shopThemeOceanDesc': 'Deep blue ocean',
  'shopThemeEmerald': 'Emerald Theme',
  'shopThemeEmeraldDesc': 'Elegant green',
  'shopThemeRoyal': 'Royal Theme',
  'shopThemeRoyalDesc': 'Royal purple',
  'shopThemeCrimson': 'Crimson Theme',
  'shopThemeCrimsonDesc': 'Bold red',
  'shopBgVault': 'Vault Background',
  'shopBgVaultDesc': 'Secure vault backdrop',
  'shopBgStars': 'Stars Background',
  'shopBgStarsDesc': 'Starry night sky',
  'shopBgNeon': 'Neon Background',
  'shopBgNeonDesc': 'Vibrant neon blue',
  'shopBgAurora': 'Aurora Background',
  'shopBgAuroraDesc': 'Multi-color aurora',
  'shopSkinSoft': 'Soft Skin',
  'shopSkinSoftDesc': 'Soft rounded corners',
  'shopSkinGlass': 'Glass Skin',
  'shopSkinGlassDesc': 'Frosted glass effect',
  'shopSkinBold': 'Bold Skin',
  'shopSkinBoldDesc': 'Bold borders',
  'shopFeatExport': 'Export data',
  'shopFeatExportDesc': 'Export documents to file',
  'shopFeatUnlimited': 'Unlimited docs',
  'shopFeatUnlimitedDesc': 'Store up to 500 documents',
  'shopFeatBackup': 'Advanced backup',
  'shopFeatBackupDesc': 'Enhanced backup & restore',
  'shopFeatExpiry': 'Expiry alerts',
  'shopFeatExpiryDesc': 'Remind before expiry date',
  'shopMenuAll': 'All',
  'shopMenuPremium': 'Premium',
  'shopMenuThemes': 'Themes',
  'shopMenuBackgrounds': 'Backgrounds',
  'shopMenuSkins': 'Skins',
  'shopMenuFeatures': 'Features',
  'shopEmptyCategory': 'No items',
  'shopOwned': 'Owned',
  'shopBuy': 'Buy',
  'shopApply': 'Apply',
  'shopActive': 'Active',
  'shopResetDefault': 'Default',
  'shopInsufficientCoins': 'Not enough points',
  'shopPurchaseSuccess': 'Purchase successful!',
  'shopAlreadyOwned': 'Already owned',
  'purchaseSuccess': 'Purchase successful',
  'purchaseFailed': 'Purchase failed',
  'coinsAdded': 'Points added',
  'coinsAddedWithBonus': 'Points added with bonus',
  'coinEarned': '+{amount} points',
  'coinRewardSub': 'Balance: {balance} points',
  'coins': 'points',
  'removeAdsUnlocked': 'Ads removed',
  'dailyRewardClaimed': 'Daily reward claimed',
  'docRewardEarned': 'Document reward earned',
  'backupRewardEarned': 'Backup reward earned',
  'spinRewardEarned': 'Spin reward earned',
  'coinPack': 'Pack {num}',
  'coinAmountTotal': '{count} points',
  'coinBonusExtra': '{base} + {bonus} bonus',
  'hotDealBadge': 'HOT',
  'bestValueBadge': 'BEST',
  'firstPurchaseBadge': '+50%',
  'earnCoinsHint': 'Or earn free points in the Shop',
  'processingPurchase': 'Processing...',
  'billingUnavailable': 'Billing unavailable',
  'productsNotFound': 'Products not found',
  'openingBilling': 'Opening billing...',
  'configTimeout': 'Config load timeout',
  'configNetworkError': 'Network error loading config',
  'billingDisabledHint': 'Buy with points in the shop',
  'documentLimitReached': 'Document limit reached. Upgrade in Shop.',
  'deleteConfirm': 'Delete this document?',
  'privacyPolicy': 'Privacy policy',
  'version': 'Version {version}',
  'darkMode': 'Dark mode',
  'lightMode': 'Light mode',
  'minutes': '{count} min',
  'oldPin': 'Old PIN',
  'newPin': 'New PIN',
  'pinChanged': 'PIN changed',
  'backupSuccess': 'Backup successful',
  'restoreSuccess': 'Restore successful',
  'restoreFailed': 'Restore failed',
  'exportRequiresPremium': 'Export feature required',
  'documentsCount': '{count} documents',
  'titleRequired': 'Please enter a document title',
  'saveSuccess': 'Document saved',
  'saveFailed': 'Save failed, please try again',
  'promoHotDeal': 'WEEKLY HOT DEAL',
  'promoTitle': 'Upgrade your vault ✨',
  'promoHotDealDesc': 'Pack {pack} — get {coins} points (+ weekly bonus)',
  'promoUnlockTarget': 'Next unlock: {item} ({price} pts)',
  'promoUnlockRemaining': 'Only {count} more points to unlock!',
  'promoBuyNow': 'Buy coins now',
  'promoBuyShort': 'Buy',
  'promoCompactTitle': 'Hot deal — extra points',
  'purchasePromoTitle': 'Special offer today',
  'purchasePromoDesc': 'Hot pack {pack}: {coins} points (+{bonus} bonus)',
  'purchaseFirstBonus': 'First purchase +50% — don\'t miss out!',
  'teaserPremiumTitle': 'Premium themes & features',
  'teaserPremiumDesc': 'Use points or buy coins to unlock',
  'shopSubtitle': 'Buy themes, skins and premium features',
  'yourWallet': 'Your point wallet',
  'earnStepDaily': 'Daily login reward',
  'dailyRewardDone': 'Claimed today',
  'privacyPolicyTitle': 'Digital Safe Privacy Policy',
  'privacyPolicyBody': 'Digital Safe stores data locally on your device with AES-256 encryption. We do not collect or upload your personal documents to any server. Payment data is processed by Google Play. The app requires camera and photo permissions to scan documents.',
};
